import esbuild from "esbuild";
import process from "process";
import {builtinModules as builtins} from "node:module";

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	// Third-party only. Plugin source imports preact/compat by name, so nothing
	// here claims a react package that is not installed. But
	// @tanstack/react-virtual, motion and zustand all import "react"
	// themselves, and those imports have to resolve somewhere. esbuild applies
	// an alias to subpaths too, so
	// "react/jsx-runtime" lands on "preact/compat/jsx-runtime" and
	// "react-dom/client" on "preact/compat/client", both of which preact ships.
	alias: {
		react: "preact/compat",
		"react-dom": "preact/compat",
	},
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod,
	// Preserve class names so constructor.name checks (e.g. UnlikelyFormatFilter) work under minification
	keepNames: prod,
	define: {
		"process.env.NODE_ENV": '"production"',
	},
	outfile: "main.js",
	plugins: [
		// Replace lodash-es barrel import with individual modules (~615 KB → ~30 KB)
		{
			name: 'lodash-es-tree-shake',
			setup(build) {
				build.onResolve({filter: /^lodash-es$/}, () => ({
					path: 'lodash-es',
					namespace: 'lodash-es-shim',
				}))
				build.onLoad({filter: /.*/, namespace: 'lodash-es-shim'}, () => ({
					contents: `
						export { default as cloneDeep } from 'lodash-es/cloneDeep';
						export { default as isEqual } from 'lodash-es/isEqual';
						export { default as merge } from 'lodash-es/merge';
					`,
					resolveDir: '.',
				}))
			},
		},
	],
	loader:{
		'.jpeg':'dataurl',
		'.jpg':'dataurl'

	}


});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
