import esbuild from "esbuild";
import process from "process";
import {builtinModules as builtins} from "node:module";
import svgr from 'esbuild-plugin-svgr'

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	// Preact in React's place. The plugin's own React surface is small - roots,
	// portals, the standard hooks, context, Fragment, StrictMode, memo - and
	// preact/compat covers all of it, but the third-party components
	// (@tanstack/react-virtual, motion, zustand, the svgr output) import "react"
	// by name, so the substitution belongs here rather than in the imports.
	// esbuild applies an alias to subpaths too, so "react/jsx-runtime" resolves
	// to "preact/compat/jsx-runtime" and "react-dom/client" to
	// "preact/compat/client", both of which preact ships.
	alias: {
		react: "preact/compat",
		"react-dom": "preact/compat",
	},
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod,
	// Preserve class names so constructor.name checks (e.g. UnlikelyFormatFilter) work under minification
	keepNames: prod,
	define: {
		"process.env.NODE_ENV": '"production"',
	},
	outfile: "main.js",
	plugins: [
		// Replace lodash-es barrel import with individual modules (~615 KB → ~30 KB)
		{
			name: 'lodash-es-tree-shake',
			setup(build) {
				build.onResolve({filter: /^lodash-es$/}, () => ({
					path: 'lodash-es',
					namespace: 'lodash-es-shim',
				}))
				build.onLoad({filter: /.*/, namespace: 'lodash-es-shim'}, () => ({
					contents: `
						export { default as cloneDeep } from 'lodash-es/cloneDeep';
						export { default as isEqual } from 'lodash-es/isEqual';
						export { default as merge } from 'lodash-es/merge';
					`,
					resolveDir: '.',
				}))
			},
		},
		svgr()
	],
	loader:{
		'.jpeg':'dataurl',
		'.jpg':'dataurl'

	}


});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
