import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import svgr from 'esbuild-plugin-svgr'

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod,
	define: {
		"process.env.NODE_ENV": '"production"',
	},
	outfile: "main.js",
	plugins: [
		// Replace lodash-es barrel import with individual modules (~615 KB → ~30 KB)
		{
			name: 'lodash-es-tree-shake',
			setup(build) {
				build.onResolve({filter: /^lodash-es$/}, () => ({
					path: 'lodash-es',
					namespace: 'lodash-es-shim',
				}))
				build.onLoad({filter: /.*/, namespace: 'lodash-es-shim'}, () => ({
					contents: `
						export { default as cloneDeep } from 'lodash-es/cloneDeep';
						export { default as isEqual } from 'lodash-es/isEqual';
						export { default as merge } from 'lodash-es/merge';
					`,
					resolveDir: '.',
				}))
			},
		},
		svgr()
	],
	loader:{
		'.jpeg':'dataurl',
		'.jpg':'dataurl'

	}


});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
