/**
 * @jest-environment node
 */
import {parseHmd, serializeHmd, HmdParseResult} from "../src/data/HmdParser";

// ─── §3 Frontmatter ─────────────────────────────────────────────────

describe("3. Frontmatter", () => {
	it("Example 1: Minimal frontmatter", () => {
		const input = `---\nblockId: "1992306556"\n---\n`;
		const result = parseHmd(input);
		expect(result.settings.blockId).toBe("1992306556");
		expect(result.settings.autoSave).toBe(true);
		expect(result.settings.header).toBe("");
		expect(result.settings.footer).toBe("");
		expect(result.units).toHaveLength(0);
	});

	it("Example 2: Full frontmatter", () => {
		const input = [
			"---",
			'blockId: "1992306556"',
			"autoSave: false",
			'header: "<b>World History</b>"',
			'footer: "<i>Generated by Historica</i>"',
			"---",
			"",
		].join("\n");
		const result = parseHmd(input);
		expect(result.settings.blockId).toBe("1992306556");
		expect(result.settings.autoSave).toBe(false);
		expect(result.settings.header).toBe("<b>World History</b>");
		expect(result.settings.footer).toBe("<i>Generated by Historica</i>");
	});
});

// ─── §4 Entry ────────────────────────────────────────────────────────

describe("4. Entry", () => {
	it("Example 3: Basic entry", () => {
		const input = [
			"---",
			'blockId: "100"',
			"---",
			"",
			"## July 14, 1789",
			"date:: 1789-07-14",
			"source:: flow-test.md",
			"",
			"The French Revolution began on July 14, 1789.",
			"",
		].join("\n");
		const result = parseHmd(input);
		expect(result.units).toHaveLength(1);
		const u = result.units[0];
		expect(u.parsedResultText).toBe("July 14, 1789");
		expect(u.time.style).toBe("unix");
		expect(/^-?\d+$/.test(u.time.value)).toBe(true);
		expect(u.filePath).toBe("flow-test.md");
		expect(u.sentence).toBe("The French Revolution began on July 14, 1789.");
		expect(u.isExpanded).toBe(false);
		expect(u.attachments).toHaveLength(0);
	});

	it("Example 4: Entry with internal state", () => {
		const input = [
			"---",
			'blockId: "100"',
			"---",
			"",
			"## September 1, 1939",
			"date:: 1939-09-01",
			"source:: user-test-ww2.md",
			"%%id: 2044819733%%",
			"%%hidden%%",
			"",
			"The war in Europe began when Germany invaded Poland on September 1, 1939.",
			"Britain and France declared war on Germany two days later.",
			"",
		].join("\n");
		const result = parseHmd(input);
		expect(result.units).toHaveLength(1);
		const u = result.units[0];
		expect(u.parsedResultText).toBe("September 1, 1939");
		expect(u.id).toBe("2044819733");
		expect(u.isHidden).toBe(true);
		expect(u.sentence).toBe(
			"The war in Europe began when Germany invaded Poland on September 1, 1939.\n" +
			"Britain and France declared war on Germany two days later."
		);
	});

	it("Example 5: Free-form date", () => {
		const input = [
			"---",
			'blockId: "100"',
			"---",
			"",
			"## The Bronze Age",
			"date:: circa 3300 BCE",
			"date-style:: free",
			"",
			"The Bronze Age began around 3300 BCE in the Near East.",
			"",
		].join("\n");
		const result = parseHmd(input);
		const u = result.units[0];
		expect(u.time.style).toBe("free");
		expect(u.time.value).toBe("circa 3300 BCE");
	});

	it("Example 6: Unix timestamp", () => {
		const input = [
			"---",
			'blockId: "100"',
			"---",
			"",
			"## Apollo 11",
			"date:: -14182940000",
			"source:: space-history.md",
			"",
			"Humans first walked on the Moon on July 20, 1969.",
			"",
		].join("\n");
		const result = parseHmd(input);
		const u = result.units[0];
		expect(u.time.style).toBe("unix");
		expect(u.time.value).toBe("-14182940000");
		expect(u.filePath).toBe("space-history.md");
	});
});

// ─── §5 Separator ────────────────────────────────────────────────────

describe("5. Separator", () => {
	it("Example 7: Two entries with separator", () => {
		const input = [
			"---",
			'blockId: "100"',
			"---",
			"",
			"## Event One",
			"date:: 2000-01-01",
			"",
			"The first event.",
			"",
			"---",
			"",
			"## Event Two",
			"date:: 2000-12-31",
			"",
			"The second event.",
			"",
		].join("\n");
		const result = parseHmd(input);
		expect(result.units).toHaveLength(2);
		expect(result.units[0].parsedResultText).toBe("Event One");
		expect(result.units[1].parsedResultText).toBe("Event Two");
	});

	it("Example 8: Single entry (no separator)", () => {
		const input = [
			"---",
			'blockId: "101"',
			"---",
			"",
			"## Only Event",
			"date:: 2020-06-15",
			"",
			"This is the only entry.",
			"",
		].join("\n");
		const result = parseHmd(input);
		expect(result.units).toHaveLength(1);
		expect(result.units[0].parsedResultText).toBe("Only Event");
	});
});

// ─── §6 Attachments ─────────────────────────────────────────────────

describe("6. Attachments", () => {
	it("Example 9: Entry with attachments", () => {
		const input = [
			"---",
			'blockId: "100"',
			"---",
			"",
			"## D-Day",
			"date:: 1944-06-06",
			"source:: ww2-notes.md",
			"%%id: 9988776655%%",
			"attachments:",
			"- [[images/d-day-beach.jpg]]",
			"- [[documents/operation-overlord.pdf]]",
			"",
			"On June 6, Allied forces landed on the beaches of Normandy in the largest",
			"amphibious invasion in military history.",
			"",
		].join("\n");
		const result = parseHmd(input);
		const u = result.units[0];
		expect(u.attachments).toHaveLength(2);
		expect(u.attachments[0].path).toBe("images/d-day-beach.jpg");
		expect(u.attachments[1].path).toBe("documents/operation-overlord.pdf");
		expect(u.id).toBe("9988776655");
		expect(u.sentence).toContain("On June 6");
	});
});

// ─── §7 Full document ───────────────────────────────────────────────

describe("7. Full document", () => {
	it("Example 10: Complete HMD file", () => {
		const input = [
			"---",
			'blockId: "1992306556"',
			"autoSave: true",
			'header: ""',
			'footer: ""',
			"---",
			"",
			"## July 14, 1789",
			"date:: 1789-07-14",
			"source:: flow-test.md",
			"%%id: 2136136417%%",
			"",
			"The French Revolution began on July 14, 1789.",
			"",
			"---",
			"",
			"## September 1, 1939",
			"date:: 1939-09-01",
			"source:: user-test-ww2.md",
			"%%id: 1998565483%%",
			"",
			"The war in Europe began when Germany invaded Poland on September 1, 1939.",
			"Britain and France declared war on Germany two days later.",
			"",
			"---",
			"",
			"## D-Day",
			"date:: 1944-06-06",
			"source:: ww2-notes.md",
			"%%id: 3344556677%%",
			"attachments:",
			"- [[images/d-day-map.png]]",
			"",
			"On June 6, Allied forces landed on the beaches of Normandy in the largest",
			"amphibious invasion in military history.",
			"",
			"---",
			"",
			"## September 2, 1945",
			"date:: 1945-09-02",
			"source:: flow-test.md",
			"%%id: 1998565484%%",
			"%%hidden%%",
			"",
			"World War II ended on September 2, 1945.",
			"",
		].join("\n");
		const result = parseHmd(input);
		expect(result.settings.blockId).toBe("1992306556");
		expect(result.settings.autoSave).toBe(true);
		expect(result.units).toHaveLength(4);
		expect(result.units[0].id).toBe("2136136417");
		expect(result.units[1].id).toBe("1998565483");
		expect(result.units[2].attachments).toHaveLength(1);
		expect(result.units[3].isHidden).toBe(true);
	});
});

// ─── §8 Edge cases ──────────────────────────────────────────────────

describe("8. Edge cases", () => {
	it("Example 11: Multi-paragraph body", () => {
		const input = [
			"---",
			'blockId: "100"',
			"---",
			"",
			"## The Renaissance",
			"date:: 1400-01-01",
			"",
			"The Renaissance was a cultural movement that began in Italy.",
			"",
			"It spread across Europe over the following centuries, fundamentally",
			"changing art, science, and philosophy.",
			"",
		].join("\n");
		const result = parseHmd(input);
		expect(result.units[0].sentence).toBe(
			"The Renaissance was a cultural movement that began in Italy.\n" +
			"\n" +
			"It spread across Europe over the following centuries, fundamentally\n" +
			"changing art, science, and philosophy."
		);
	});

	it("Example 12: Entry with no source field", () => {
		const input = [
			"---",
			'blockId: "100"',
			"---",
			"",
			"## Some Event",
			"date:: 2023-01-15",
			"",
			"A manually added entry with no source file.",
			"",
		].join("\n");
		const result = parseHmd(input);
		expect(result.units[0].filePath).toBe("");
	});

	it("Example 13: Markdown formatting in body", () => {
		const input = [
			"---",
			'blockId: "100"',
			"---",
			"",
			"## The Moon Landing",
			"date:: 1969-07-20",
			"source:: space.md",
			"",
			'Neil Armstrong said: *"That\'s one small step for man, one giant leap',
			'for mankind."* The **Apollo 11** mission was a success.',
			"",
		].join("\n");
		const result = parseHmd(input);
		expect(result.units[0].sentence).toContain('*"That\'s one small step');
		expect(result.units[0].sentence).toContain("**Apollo 11**");
	});

	it("Example 14: Empty file (frontmatter only)", () => {
		const input = `---\nblockId: "999"\n---\n`;
		const result = parseHmd(input);
		expect(result.settings.blockId).toBe("999");
		expect(result.units).toHaveLength(0);
	});

	it("Example 15: Unknown frontmatter fields preserved", () => {
		const input = [
			"---",
			'blockId: "100"',
			'customField: "hello"',
			"---",
			"",
			"## Test",
			"date:: 2020-01-01",
			"",
			"Body text.",
			"",
		].join("\n");
		const result = parseHmd(input);
		expect(result._extraFrontmatter).toBeDefined();
		expect(result._extraFrontmatter).toContainEqual(["customField", "hello"]);
	});

	it("Example 16: Unknown comment fields preserved", () => {
		const input = [
			"---",
			'blockId: "100"',
			"---",
			"",
			"## Test",
			"date:: 2020-01-01",
			"%%id: abc%%",
			"%%customTag: some value%%",
			"",
			"Body text.",
			"",
		].join("\n");
		const result = parseHmd(input);
		expect(result.units[0].id).toBe("abc");
		expect(result._extraComments?.get("abc")).toContainEqual("%%customTag: some value%%");
	});
});

// ─── Round-trip ─────────────────────────────────────────────────────

describe("Round-trip", () => {
	const roundTripCases: [string, string][] = [
		["single entry", [
			"---",
			'blockId: "100"',
			"autoSave: true",
			'header: ""',
			'footer: ""',
			"---",
			"",
			"## Apollo 11",
			"date:: -14182940000",
			"source:: space-history.md",
			"%%id: abc123%%",
			"",
			"Humans first walked on the Moon on July 20, 1969.",
			"",
		].join("\n")],
		["two entries", [
			"---",
			'blockId: "100"',
			"autoSave: true",
			'header: ""',
			'footer: ""',
			"---",
			"",
			"## Event One",
			"date:: 946684800000",
			"%%id: e1%%",
			"",
			"The first event.",
			"",
			"---",
			"",
			"## Event Two",
			"date:: 978307200000",
			"%%id: e2%%",
			"",
			"The second event.",
			"",
		].join("\n")],
		["entry with free date", [
			"---",
			'blockId: "100"',
			"autoSave: true",
			'header: ""',
			'footer: ""',
			"---",
			"",
			"## The Bronze Age",
			"date:: circa 3300 BCE",
			"date-style:: free",
			"%%id: bronze%%",
			"",
			"The Bronze Age began around 3300 BCE in the Near East.",
			"",
		].join("\n")],
		["entry with attachments and hidden", [
			"---",
			'blockId: "100"',
			"autoSave: true",
			'header: ""',
			'footer: ""',
			"---",
			"",
			"## D-Day",
			"date:: -804556800000",
			"source:: ww2-notes.md",
			"%%id: dday%%",
			"%%hidden%%",
			"attachments:",
			"- [[images/d-day-beach.jpg]]",
			"",
			"On June 6, Allied forces landed.",
			"",
		].join("\n")],
	];

	it.each(roundTripCases)("parse then serialize is stable: %s", (_name, input) => {
		const parsed = parseHmd(input);
		const serialized = serializeHmd(parsed);
		const reparsed = parseHmd(serialized);
		const reserialized = serializeHmd(reparsed);
		// Idempotent: second serialization matches first
		expect(reserialized).toBe(serialized);
	});

	it.each(roundTripCases)("structural equality after round-trip: %s", (_name, input) => {
		const parsed = parseHmd(input);
		const serialized = serializeHmd(parsed);
		const reparsed = parseHmd(serialized);

		expect(reparsed.settings).toEqual(parsed.settings);
		expect(reparsed.units.length).toBe(parsed.units.length);
		for (let i = 0; i < parsed.units.length; i++) {
			expect(reparsed.units[i].parsedResultText).toBe(parsed.units[i].parsedResultText);
			expect(reparsed.units[i].sentence).toBe(parsed.units[i].sentence);
			expect(reparsed.units[i].time).toEqual(parsed.units[i].time);
			expect(reparsed.units[i].filePath).toBe(parsed.units[i].filePath);
			expect(reparsed.units[i].id).toBe(parsed.units[i].id);
			expect(reparsed.units[i].isHidden).toBe(parsed.units[i].isHidden);
			expect(reparsed.units[i].attachments.map((a: any) => a.path))
				.toEqual(parsed.units[i].attachments.map((a: any) => a.path));
		}
	});
});
