name: "build doc"
on:
    push:
        branches:
            - master

jobs:
    build-doc:
        runs-on: ubuntu-latest
        if: "contains(github.event.head_commit.message,'doc:code:')"
        permissions: write-all
        steps:
            -   name: check out this repo
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0


            -   name: set up node
                uses: actions/setup-node@v4
                with:
                    node-version: '21'

            -   name: build and deploy doc
                env:
                    CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                    CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                run:  |
                    yarn install
                    npx typedoc
                    npx wrangler pages deploy --config wrangler_code_doc.toml
                    ls -al
                    
                    
