name: "build doc"
on:
    push:
        branches:
            - master

jobs:
    build-doc:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message,'doc: ')"
        permissions: write-all
        steps:
            -   name: "check out quartz custom template "
                uses: actions/checkout@v4
                with:
                    repository: "nhannht/knowledgebase-template"
                    fetch-depth: 0
                    ref: knowledgebase
                    path: quartz

            -   name: check out this repo
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0
                    path: historica


            -   name: set up node
                uses: actions/setup-node@v4
                with:
                    node-version: '20'

            -   name: build and deploy doc
                env:
                    CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                    CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                run:  |
                    cd quartz
                    npm install
                    npm install wrangler
                    cp ../historica/historica_document/* ./content/ -r
                    cp ../historica/quartz.config.ts ./
                    cp ../historica/quartz.layout.ts ./
                    cp ../historica/wrangler.toml ./
                    npx  quartz build
                    npx wrangler pages deploy
                    


