name: "build doc"
on:
    push:
        branches:
            - master

jobs:
    build-doc:
        runs-on: ubuntu-latest
        if: "contains(github.event.head_commit.message,'doc:')"
        permissions: write-all
        steps:
            -   name: "check out quartz custom template "
                uses: actions/checkout@v4
                with:
                    repository: "nhannht/quartz"
                    fetch-depth: 0
                    ref: v4
                    path: quartz

            -   name: check out this repo
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0
                    path: historica


            -   name: set up node
                uses: actions/setup-node@v4
                with:
                    node-version: '20'

            -   name: setup java
                uses: actions/setup-java@v4
                with:
                    distribution: 'temurin' # See 'Supported distributions' for available options
                    java-version: '21'

            -   name: Setup Graphviz
                uses: ts-graphviz/setup-graphviz@v2

            -   name: build and deploy doc
                env:
                    CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                    CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                run:  |
                    cd quartz
                    yarn 
                    yarn add wrangler
                    cp ../historica/* ./content/ -r
                    cp ../historica/quartz.config.ts ./
                    cp ../historica/quartz.layout.ts ./
                    cp ../historica/wrangler_config/wrangler_user_doc.toml ./wrangler.toml
                    npx  quartz build
                    npx wrangler pages deploy --branch=nhancoolcoolcool
                    
                    cd ../historica/
                    yarn
                    npx typedoc
                    cp ./wrangler_config/wrangler_code_doc.toml ./wrangler.toml
                    npx wrangler pages deploy --branch=main
                    
                    
                    


